### ISSUE TITLE
[ERROR]: Environment Variable of MINIO_ACCESS_KEY

### ISSUE THREAD

**Issue by cftang0827** [milvus-io/milvus-docs#2251]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Milvus standlone version: `milvusdb/milvus:v2.2.12`
Milvus Python SDK version: 
```py
>>> pymilvus.__version__
'2.2.14'
```

I am using docker compose to launch milvus standalone version, and I want to use S3 as blob storage. Therefore, according to the [documents](https://milvus.io/docs/v2.3.0-beta/configure_minio.md), I need to specify the environment variable `MINIO_ACCESS_KEY` & `MINIO_SECRET_KEY` which represent AWS's `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` 

The setting is like 
```yaml
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: s3.ap-northeast-1.amazonaws.com
      MINIO_PORT: 80
      MINIO_BUCKET_NAME: ds-milvus
      MINIO_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxx
      MINIO_SECRET_KEY: xxxxxxxxxxxxxxxxxxx
 ```
 
 However, I keep getting this credential error
 ```
milvus-standalone  | [2023/07/27 07:19:36.187 +00:00] [WARN] [storage/minio_chunk_manager.go:110] ["failed to check blob bucket exist"] [bucket=ds-milvus] [error="Access Denied."]
milvus-standalone  | [2023/07/27 07:19:36.244 +00:00] [WARN] [storage/minio_chunk_manager.go:110] ["failed to check blob bucket exist"] [bucket=ds-milvus] [error="Access Denied."]
milvus-standalone  | [2023/07/27 07:19:36.283 +00:00] [WARN] [storage/minio_chunk_manager.go:110] ["failed to check blob bucket exist"] [bucket=ds-milvus] [error="Access Denied."]
```

Then I tried to log into milvus standalone container, and see the the `milvus.yaml` config
https://github.com/milvus-io/milvus/blob/b986e3af81978b7238f7df7a5517cfbf7ab8fbde/configs/milvus.yaml#L69-L70

```yaml
minio:
  address: localhost # Address of MinIO/S3
  port: 9000 # Port of MinIO/S3
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
 ```
 
 Seems like the environment variable of access id and secret key should be  `MINIO_ACCESS_KEY_ID` & `MINIO_SECRET_ACCESS_KEY` rather than `MINIO_ACCESS_KEY` & `MINIO_SECRET_KEY`
 
 Looks like environment variable is composed by config file with `MINIO_*` prefix.
 
 And after I modified to the `MINIO_ACCESS_KEY_ID` & `MINIO_SECRET_ACCESS_KEY` , it works!
 Can you verify it as well? if there's a documents error, I am glad to create a PR to fix it. Or there could be some place that I didn't notice. 
 
 Thank you.
 

### Suggestion

If it's documents error, we should update it, or people will spend a lot of time dealing with the error.
