### ISSUE TITLE
[Suggestion] Add a GPU related question to FAQ

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus-docs#716]
Add the following q&a to https://milvus.io/docs/v1.1.1/milvus_docker-gpu.md#FAQ:

Q - How to assign GPU devices to index/search?
A - In **server_config.yaml** file under /home/$USER/milvus/conf, you can assign GPU devices to index/search. See example:
```
gpu:
  enable: true
  cache_size: 10GB
  gpu_search_threshold: 0
  search_devices:
    - gpu0
    - gpu1
  build_index_devices:
    - gpu2
    - gpu3
 ```
Note: gpu0,1,2,3 are first 4 gpu from the list of gpu devices assigned to the docker container.

Add above to both Chinese & English FAQ.
